changing in col alignment and invalid values for Moksha, Soikkola_Ingrian, Central Veps and Komi Syrian
bedlan/uratyp-1 pull request #2
Opened 2024-06-05 12:36 UTC by HedvigS

2024-06-05 12:58 UTC, xrotwang requested changes
Can we please keep changes to this repos minimal? It's really hard to keep track of what actually happened when all lines in sheets change.

2024-06-05 12:58 UTC, xrotwang commented on raw/GB/language-tables/Komi_Zyrian.csv
> +GB286,Can polar interrogation be indicated by overt verbal morphology only?,?,,,
It seems the value has been changed to `?`. Isn't this PR only intended to change formatting?

2024-06-05 12:58 UTC, xrotwang commented on raw/GB/language-tables/Central_Veps.csv
> -GB400,Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?,0,Grünthal 2015: 121–126,,
It looks like all feature titles are simply cut at the first comma. This cannot be intended, right?

2024-06-05 12:58 UTC, xrotwang commented on raw/GB/language-tables/Central_Veps.csv
> +ID,Feature,Value,Source,Comment,Example,,,
Why add un-named, empty columns to each row?

2024-06-05 12:58 UTC, xrotwang commented on raw/GB/language-tables/Moksha.csv
> -GB306,Is there a phonologically independent non-bipartite reciprocal pronoun?, two + two)?,0,Bartens 1999:114,,,,
Again, looks like the title is simply cut at the first comma, rather than quoting it and keeping the inner comma.

2024-06-05 13:01 UTC, HedvigS commented
> Can we please keep changes to this repos minimal? It's really hard to keep track of what actually happened when all lines in sheets change.

If you can help make these changes in a more minimal way, be my guest. I am just trying to solve the problems on my desk. I don't know how to do it any other way right now.

2024-06-05 13:02 UTC, HedvigS commented
I moved the content left so that the value aligned with value. As you've noted @xrotwang that means bad things for the Feature col. For me, that's fine because I only use the ID col anyway. 

If you have another solution to the problem then please posit a new branch and PR.

2024-06-05 13:04 UTC, HedvigS commented on raw/GB/language-tables/Komi_Zyrian.csv
> +GB286,Can polar interrogation be indicated by overt verbal morphology only?,?,,,
The value was an invalid "1?". Years ago when we did changes to the sheets at google drive, we changed such instances to "?" so I did so here too.

2024-06-05 13:06 UTC, xrotwang commented
> If you can help make these changes in a more minimal way, be my guest. I am just trying to solve the problems on my desk. I don't know how to do it any other way right now.

Here's what I did the last time:
```diff
diff --git a/raw/GB/language-tables/Finnish.csv b/raw/GB/language-tables/Finnish.csv
index b916366..4ecc450 100644
--- a/raw/GB/language-tables/Finnish.csv
+++ b/raw/GB/language-tables/Finnish.csv
@@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker (‘particle’ or ‘auxili
 GB303,Is there a phonologically free antipassive marker (‘particle’ or ‘auxiliary’)?,0,VISK:in passim,,,^M
 GB304,Can the agent be expressed overtly in a passive clause?,0,VISK § 1315-1346,,,^M
 GB305,Is there a phonologically independent reflexive marker?,1,VISK § 730,,GB305,^M
-GB306,Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other,  two + two)?,1,VISK § 732,,GB306^M
+GB306,"Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other,  two + two)?",1,VISK § 732,,GB306^M
 GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,VISK § 1523-1550,,,^M
 GB312,Is there overt morphological marking on the verb dedicated to mood?,1,VISK § 115,,GB312,^M
 GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Mervi de Heer (p.c. 2019),,,^M
diff --git a/raw/GB/language-tables/Moksha.csv b/raw/GB/language-tables/Moksha.csv
index 142ac42..fb00644 100644
--- a/raw/GB/language-tables/Moksha.csv
+++ b/raw/GB/language-tables/Moksha.csv
@@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker ('particle' or 'auxiliary')?
 GB303,Is there a phonologically free antipassive marker ('particle' or 'auxiliary')?,0,Bartens 1999:in passim,,,,,^M
 GB304,Can the agent be expressed overtly in a passive clause?,1,Toldova et al. 2018:490,,GB304,,,^M
 GB305,Is there a phonologically independent reflexive pronoun?,1,Bartens 1999:114,,GB305,,,^M
-GB306,Is there a phonologically independent non-bipartite reciprocal pronoun?, two + two)?,0,Bartens 1999:114,,,,^M
+GB306,"Is there a phonologically independent non-bipartite reciprocal pronoun?, two + two)?",0,Bartens 1999:114,,,,^M
 GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,Bartens 1999:127-131,,,,,^M
 GB312,Is there overt morphological marking on the verb dedicated to mood?,1,Bartens 1999:132-140,,GB080,,,^M
 GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Bartens 1999:111-113,,,,,^M
diff --git a/raw/GB/language-tables/Soikkola_Ingrian.csv b/raw/GB/language-tables/Soikkola_Ingrian.csv
index 4230b52..c4b393a 100644
--- a/raw/GB/language-tables/Soikkola_Ingrian.csv
+++ b/raw/GB/language-tables/Soikkola_Ingrian.csv
@@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker (‘particle’ or ‘auxili
 GB303,Is there a phonologically free antipassive marker (‘particle’ or ‘auxiliary’)?,0,Eva Saar (p.c. 2023),,^M
 GB304,Can the agent be expressed overtly in a passive clause?,0,Eva Saar (p.c. 2023),,^M
 GB305,Is there a phonologically independent reflexive marker?,1,Eva Saar (p.c. 2023),,GB305^M
-GB306,Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other, two + two)?,0,Eva Saar (p.c. 2023),^M
+GB306,"Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other, two + two)?",0,Eva Saar (p.c. 2023),^M
 GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,Eva Saar (p.c. 2023),,^M
 GB312,Is there overt morphological marking on the verb dedicated to mood?,1,Eva Saar (p.c. 2023),,GB312^M
 GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Eva Saar (p.c. 2023),,^M
```

2024-06-05 13:12 UTC, HedvigS commented
> > If you can help make these changes in a more minimal way, be my guest. I am just trying to solve the problems on my desk. I don't know how to do it any other way right now.
> 
> Here's what I did the last time:
> 
> ```diff
> diff --git a/raw/GB/language-tables/Finnish.csv b/raw/GB/language-tables/Finnish.csv
> index b916366..4ecc450 100644
> --- a/raw/GB/language-tables/Finnish.csv
> +++ b/raw/GB/language-tables/Finnish.csv
> @@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker (‘particle’ or ‘auxili
>  GB303,Is there a phonologically free antipassive marker (‘particle’ or ‘auxiliary’)?,0,VISK:in passim,,,^M
>  GB304,Can the agent be expressed overtly in a passive clause?,0,VISK § 1315-1346,,,^M
>  GB305,Is there a phonologically independent reflexive marker?,1,VISK § 730,,GB305,^M
> -GB306,Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other,  two + two)?,1,VISK § 732,,GB306^M
> +GB306,"Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other,  two + two)?",1,VISK § 732,,GB306^M
>  GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,VISK § 1523-1550,,,^M
>  GB312,Is there overt morphological marking on the verb dedicated to mood?,1,VISK § 115,,GB312,^M
>  GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Mervi de Heer (p.c. 2019),,,^M
> diff --git a/raw/GB/language-tables/Moksha.csv b/raw/GB/language-tables/Moksha.csv
> index 142ac42..fb00644 100644
> --- a/raw/GB/language-tables/Moksha.csv
> +++ b/raw/GB/language-tables/Moksha.csv
> @@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker ('particle' or 'auxiliary')?
>  GB303,Is there a phonologically free antipassive marker ('particle' or 'auxiliary')?,0,Bartens 1999:in passim,,,,,^M
>  GB304,Can the agent be expressed overtly in a passive clause?,1,Toldova et al. 2018:490,,GB304,,,^M
>  GB305,Is there a phonologically independent reflexive pronoun?,1,Bartens 1999:114,,GB305,,,^M
> -GB306,Is there a phonologically independent non-bipartite reciprocal pronoun?, two + two)?,0,Bartens 1999:114,,,,^M
> +GB306,"Is there a phonologically independent non-bipartite reciprocal pronoun?, two + two)?",0,Bartens 1999:114,,,,^M
>  GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,Bartens 1999:127-131,,,,,^M
>  GB312,Is there overt morphological marking on the verb dedicated to mood?,1,Bartens 1999:132-140,,GB080,,,^M
>  GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Bartens 1999:111-113,,,,,^M
> diff --git a/raw/GB/language-tables/Soikkola_Ingrian.csv b/raw/GB/language-tables/Soikkola_Ingrian.csv
> index 4230b52..c4b393a 100644
> --- a/raw/GB/language-tables/Soikkola_Ingrian.csv
> +++ b/raw/GB/language-tables/Soikkola_Ingrian.csv
> @@ -150,7 +150,7 @@ GB302,Is there a phonologically free passive marker (‘particle’ or ‘auxili
>  GB303,Is there a phonologically free antipassive marker (‘particle’ or ‘auxiliary’)?,0,Eva Saar (p.c. 2023),,^M
>  GB304,Can the agent be expressed overtly in a passive clause?,0,Eva Saar (p.c. 2023),,^M
>  GB305,Is there a phonologically independent reflexive marker?,1,Eva Saar (p.c. 2023),,GB305^M
> -GB306,Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other, two + two)?,0,Eva Saar (p.c. 2023),^M
> +GB306,"Is there a phonologically independent reciprocal marker that does not consist of two quantifiers (e.g. each + other, two + two)?",0,Eva Saar (p.c. 2023),^M
>  GB309,"Are there multiple past or multiple future tenses, distinguishing distance from Time of Reference?",0,Eva Saar (p.c. 2023),,^M
>  GB312,Is there overt morphological marking on the verb dedicated to mood?,1,Eva Saar (p.c. 2023),,GB312^M
>  GB313,Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?,0,Eva Saar (p.c. 2023),,^M
> ```

Would you be able to make a branch today that sorts out the column alignment problems for Moksha, Soikkola_Ingrian and Central Veps and file a PR for @@MiinaNo to review?

2024-06-05 13:49 UTC, HedvigS commented
@xrotwang I'm happy to close this PR and for you to address this in a new branch and PR.

In the meantime, since we don't care about the feature col over at glottobank/grambank I'm going ahead with https://github.com/glottobank/Grambank/pull/2773 which is based on this branch

2024-06-05 13:59 UTC, xrotwang commented
Unfortunately changing the delimiter for Central_Veps from semicolon to comma - without quoting the fields appropriately - introduced quite a few more problematic feature titles in this file.

2024-06-05 14:00 UTC, closed without merging

2024-06-05 14:39 UTC, HedvigS commented
> Unfortunately changing the delimiter for Central_Veps from semicolon to comma - without quoting the fields appropriately - introduced quite a few more problematic feature titles in this file.

Okay. I'm sorry about that. How would you like to proceed?  Would you like to start by reverting https://github.com/bedlan/uratyp-1/pull/1/commits/1abcc4223775084826d1b7d6df6298603d811bd9 ?

2024-06-05 14:47 UTC, xrotwang commented
I won't have any more time for that today. Will think about what to do tomorrow.

2024-06-06 05:59 UTC, xrotwang commented
> How would you like to proceed?

@HedvigS as far as I can tell, you have all you need for the next Grambank release, right? So dealing with the data in this repos is only relevant for the next UraTyp release.

2024-06-06 10:31 UTC, HedvigS commented
> > How would you like to proceed?
> 
> @HedvigS as far as I can tell, you have all you need for the next Grambank release, right? So dealing with the data in this repos is only relevant for the next UraTyp release.

Genau. 

It will also be relevant also for future syncing UraTyp -> Grambank and Grambank -> UraTyp (#9 ). I figure it'd be nice to solve this (#5 and #4 ) within the next few weeks so that it doesn't drag out.

2024-06-06 10:34 UTC, xrotwang commented
I would prefer to do future syncing of UraTyp data based on the CLDF dataset of released versions of UraTyp.

2024-06-06 10:37 UTC, HedvigS commented
> I would prefer to do future syncing of UraTyp data based on the CLDF dataset of released versions of UraTyp.

That's not what I thought we said we'd be doing, so that's why I've been confused and have been focusing on syncing the raw before release. I think @miinano and the UraTyp should decide ultimately here on how we should do next time.